sudo: false
language: ruby
cache: bundler
bundler_args: --without development
dist: precise
rvm:
  - 2.3.5
addons:
  apt:
    sources:
      - elasticsearch-1.7
    packages:
      - elasticsearch
  code_climate:
    repo_token: 8fdbc26f64a4535d461b9a5bf1c4044fb7780c684edcd07c017d4b4616957a93
  artifacts:
    debug: true
    paths:
      - ./log/test.log
      - $(git ls-files -o coverage/ | tr "\n" ":")
      - $(git ls-files -o tmp/capybara | tr "\n" ":")
services:
  - redis-server
before_script:
  - mysql -e 'create database usasearch_test;'
  - mysql -u travis -D usasearch_test < db/structure.sql
  - cp -p config/travis/database.yml config/database.yml
  - bash -x config/travis/setup-elasticsearch.sh && curl localhost:9200
  - RAILS_ENV=test bundle exec rake usasearch:elasticsearch:create_indexes
notifications:
  slack: blue-beacon:hjGCVYxzrNPDo0KrHzMyVwNS
