version: '3.8'

services:
  app:
    build: .
    depends_on:
      - elasticsearch6
      - elasticsearch7
      - mysql
      - redis
    command: bin/rails server --binding 0.0.0.0
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/app

  elasticsearch6:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.9
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_6_data:/usr/share/elasticsearch6/data
    ports:
      - 9268:9200

  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.license.self_generated.type=trial
      - xpack.monitoring.enabled=false
      - xpack.security.enabled=false
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_7_data:/usr/share/elasticsearch7/data
    ports:
      - 9277:9200

  kibana6:
    image: docker.elastic.co/kibana/kibana:6.8.9
    depends_on:
      - elasticsearch6
    ports:
      - 5668:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch6:9200

  mysql:
    image: mysql:5.6
    volumes:
      - ./docker/my.cnf:/etc/my.cnf
      - db_data:/var/lib/mysql/data
    ports:
      - 3306:3306
    env_file:
      - .env/development/mysql

  redis:
    image: redis:5.0.9
    ports:
      - 6379:6379

  tika:
    image: apache/tika:1.21
    ports:
      - 9998:9998

  resque-web:
    command: 'bundle exec resque-web ./lib/setup_resque.rb -F -r redis:6379'
    build: .
    depends_on:
      - redis
    ports:
      - 5678:5678
    environment:
      - PIDFILE=./resque-web.pid

  resque-workers:
    command: 'bundle exec rake environment resque:work'
    build: .
    depends_on:
      - elasticsearch6
      - mysql
      - redis
    env_file:
      - .env/development/app
      - .env/development/resque

  resque-scheduler:
    command: 'bundle exec rake resque:scheduler'
    build: .
    depends_on:
      - elasticsearch6
      - mysql
      - redis
    env_file:
      - .env/development/app
      - .env/development/resque

volumes:
  db_data:
  es_6_data:
  es_7_data:
  gem_cache:
