default: &DEFAULT
  :from_email: no-reply@support.digitalgov.gov
  :from_name:  Search.gov Team
  :base_url_params:
    :protocol: https
    :host: search.usa.gov

development:
  <<: *DEFAULT

test:
  <<: *DEFAULT

production:
  <<: *DEFAULT
  :admin_email: usagov@mail.usasearch.howto.gov
