defaults: &defaults
  host: localhost
  port: 6379

development:
  <<: *defaults

test:
  <<: *defaults
  port: <%= (ENV['CIRCLECI'] || ENV['TRAVIS']) ? 6379 : 6380 %>

cucumber:
  <<: *defaults

production:
  <<: *defaults
