production:
  SitemapMonitorJob:
    cron: "0 */4 * * *"
  ClickMonitorJob:
    cron: "0 7 * * 0"
  ElasticsearchDeleteByQueryJob:
    cron: "0 1 * * *" # Run every day at 1AM
  OpensearchDeleteByQueryJob:
    cron: "0 2 * * *" # Run every day at 2AM
