production:
  SitemapMonitorJob:
    cron: "0 */4 * * *"
  ClickMonitorJob:
    cron: "0 7 * * 0"
  ElasticsearchDeleteByQueryJob:
    cron: "0 3 * * *" # Run every day at 3AM UTC (10PM ET)
  OpensearchDeleteByQueryJob:
    cron: "0 4 * * *" # Run every day at 4AM UTC (11PM ET)
